services:
  - type: worker
    name: bluebot-md
    runtime: node
    repo: https://github.com/Vhadau2011/BLUEBOT-MD
    branch: main
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
